import { ArrowUpRight, BarChart3, BookOpen, CalendarDays, ChevronDown, CircleHelp, Command, CreditCard, GraduationCap, LayoutDashboard, MoreHorizontal, Search, Settings2, Users } from "lucide-react";

/** Replace these CSS mockups with real screenshots in public/projects/{slug}/ when available. */
export function TrainingPreview({ compact = false }: { compact?: boolean }) {
  return <div className={`training-preview ${compact ? "preview-compact" : ""}`}>
    <div className="browser-chrome"><span className="browser-lights"><i /><i /><i /></span><span className="browser-address">app.training-center.example / overview</span><MoreHorizontal size={15} /></div>
    <div className="dashboard-ui">
      <aside className="dashboard-sidebar"><div className="dashboard-brand"><span className="dashboard-brand-mark"><GraduationCap size={17} /></span> <strong>academy<span>OS</span></strong></div><div className="dashboard-side-items"><span className="selected"><LayoutDashboard size={15} /> Overview</span><span><Users size={15} /> Students</span><span><BookOpen size={15} /> Courses</span><span><CalendarDays size={15} /> Schedule</span><span><CreditCard size={15} /> Finance</span></div><div className="dashboard-side-bottom"><Settings2 size={14} /> Settings <CircleHelp size={14} /></div></aside>
      <div className="dashboard-main"><div className="dashboard-hello"><div><small>MONDAY, 16 MARCH</small><h3>Good morning, Sewar <span>✦</span></h3><p>Here&apos;s what&apos;s happening at your center.</p></div><span className="dashboard-period">This month <ChevronDown size={12} /></span></div><div className="dashboard-metrics"><div><span>Active students</span><strong>248</strong><small>↗ 12 this month</small></div><div><span>Upcoming classes</span><strong>32</strong><small>Across 6 tracks</small></div><div><span>Monthly revenue</span><strong>JD 8,420</strong><small>↗ 8.2% vs. last month</small></div></div><div className="dashboard-lower"><div className="schedule-panel"><div className="panel-heading"><strong>Today&apos;s schedule</strong><CalendarDays size={13} /></div><div className="schedule-row"><time>09:00</time><span className="schedule-line violet"/><div><strong>Full Stack Web Development</strong><small>Room 02 · A. Haddad</small></div></div><div className="schedule-row"><time>11:30</time><span className="schedule-line cyan"/><div><strong>React Fundamentals</strong><small>Room 04 · L. Saleh</small></div></div><div className="schedule-row"><time>14:00</time><span className="schedule-line amber"/><div><strong>Database Design</strong><small>Room 01 · M. Al-Rashid</small></div></div></div><div className="enrollment-panel"><div className="panel-heading"><strong>Enrollment</strong><BarChart3 size={13} /></div><div className="chart-bars">{[36,53,42,67,59,76,64,84,69,90,77,96].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>Jan</span><span>Jun</span><span>Dec</span></div></div></div></div>
    </div>
  </div>;
}

export function SubhPreview({ compact = false }: { compact?: boolean }) {
  return <div className={`subh-preview ${compact ? "preview-compact" : ""}`}>
    <div className="subh-paper"><div className="subh-top"><span className="subh-logo">صُبح<span>.</span></span><nav aria-label="Preview navigation"><span>الكتب</span><span>المجموعات</span><span>من نحن</span></nav><span className="subh-search"><Search size={15} /></span></div><div className="subh-editorial"><div className="subh-copy"><span className="subh-eyebrow">READ · LEARN · GROW</span><h3>Stories that<br/>stay with you<span>.</span></h3><p>Thoughtful books for curious minds, in Arabic and English.</p><span className="subh-fake-button">Explore the collection <ArrowUpRight size={15}/></span></div><div className="subh-art"><div className="book-back"/><div className="book-cover"><span className="book-small">صُبح للنشر</span><div className="book-motif"><span/><span/><span/></div><strong>بين<br/>السطور</strong><small>رحلة في عوالم المعرفة</small></div><div className="book-caption">A little room to wonder.</div></div></div><div className="subh-bottom"><span><BookOpen size={13}/> Curated collection</span><span><Command size={13}/> عربي / English</span><span>01 / 03</span></div></div>
  </div>;
}
